site_name: KubeFox
site_url: https://docs.kubefox.io
repo_url: https://github.com/xigxog/kubefox
repo_name: xigxog/kubefox
# edit_uri: ""
site_description: Documentation for KubeFox
site_author: John Long
copyright: Copyright © XigXog

nav:
  - index.md
  - quickstart.md
  - concepts.md
  - design.md
  - Reference:
      - reference/api.md
      - reference/protobuf.md

extra:
  homepage: https://kubefox.io
  social:
    - icon: fontawesome/solid/house
      link: https://kubefox.io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/xigxog/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kubefox
    - icon: fontawesome/brands/github
      link: https://github.com/xigxog/kubefox

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: images/kubefox-logo-black.png
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides
  font:
    text: Nunito
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - toc.integrate

plugins:
  - search
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'

markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      auto_title: true
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - scripts/refresh_on_toggle_dark_light.js
