title: KubeFox Docs
theme: just-the-docs
color_scheme: dark
# logo: /assets/images/logo.png
favicon_ico: favicon.ico

url: "https://docs.kubefox.io"
email: info@xigxog.io

description: >-
  KubeFox comprises an open-source Kubernetes runtime coupled with a toolset
  which will provide: zero trust, scale-to-zero facilities, versioned
  deployments, configuration management, compliance administration,
  verification, and validation, built-in SBOM, code provenance, and tampering
  controls, robust and integrated metrics, tracing, logging, auditing, and
  monitoring.

# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-mermaid

mermaid:
  src: https://cdn.jsdelivr.net/npm/mermaid@10
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
